branches:
  only:
    - master
    - rust-0.9
    - rust-0.10
    - rust-mac

env:
  global:
    - secure: jDCYERbsezNSosvJ8nPticN/IgdSgBMARDYBMRP2hvV86vcWxeMPXXkrLFRiHFxRs3bwN35kziZwKnrfu5UC2efG5Tj13nJIuAeOLrHUWuP5R68gRum4jDiDFo5B4ic9kEgbV0Ltxcw7/fka9dw4BfVRy3cJUk21RuiRLwBxbqU=

before_install:
  - yes | sudo apt-key adv --fetch-keys http://repos.codelite.org/CodeLite.asc
  - yes | sudo apt-add-repository 'deb http://llvm.org/apt/precise/ llvm-toolchain-precise-3.4 main'
  - yes | sudo apt-add-repository 'deb http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu precise main'
  - yes | sudo apt-add-repository 'deb http://repos.codelite.org/wx3.0/ubuntu/ precise universe'
  - sudo apt-get update
install:
  - curl -s https://static.rust-lang.org/rustup.sh | sudo sh
  - sudo ldconfig
  - sudo apt-get install libwxgtk3.0-0-unofficial libwxgtk3.0-dev
  - sudo apt-get install --force-yes libclang-3.4-dev
script:
  - mkdir -p build
  - cd build
  - cmake ..
  - make VERBOSE=1
  - make doc

after_script:
  - curl http://www.rust-ci.org/artifacts/put?t=$RUSTCI_TOKEN | sh
